### ISSUE TITLE
联系不到，在这里提问一下[不得不占用一下issue]

### ISSUE THREAD

**Issue by xujianhai** [nighca/universal-diff#5]
很喜欢你的那个demo网页上的比较效果，是否可以合到主分支上，一起对外提供使用？

**Comment by nighca** [comment]
@xujianhai 这个 demo 页面的代码在一个单独的 repo 里：[differ](https://github.com/nighca/differ)，也是基于 universal-diff 的比较功能实现的，额外做的是把 universal-diff compare 的结果组织成 DOM 结构展示到页面上。

不过因为那个 repo 单纯是为了作为一个 demo，所以实现比较粗糙，可用性也不是很强。如果你那也是要类似的效果的话，可以参考它的实现，主要逻辑在 [`differ.js`](https://github.com/nighca/differ/blob/master/js/differ.js)

**Comment by xujianhai** [comment]
我看到了这个页面, 应该就是你吧 ： https://www.npmjs.com/~nighca， 我发现 cli 都有npm包，但是 web版本的 differ 并没有相应的npm包

**Comment by xujianhai** [comment]
我的使用出现了一个问题
diffrender.js 
`
var diff = require('universal-diff')



    var compare = diff.compare;

    var render = function(template, vars){
        return template.replace(/\$\{([^\{\}]*)\}/g, function(_, name){
            return vars[name.trim()] || '';
        });
    };

    var encodeHTML = function(str){
        return str.replace(/&/g, "&gt;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/ /g, "&nbsp;")
            .replace(/\'/g, "'")
            .replace(/\"/g, "&quot;")
            .replace(/\n/g, "<br>");
    };

    // simple split
    var simpleSplit = function(cnt){
        return cnt.split('');
    };

    // participle code / word
    var participle = function(cnt){
        var arr = [];
        for(var i = 1, l = cnt.length, pos = 0; i < l; i++){
            var isPlainPattern = /[\w\_\$]+/,
                isPrevPlain = isPlainPattern.test(cnt[i-1]),
                isPlain = isPlainPattern.test(cnt[i]);

            if(
                !(isPrevPlain && isPlain)
            ){
                arr.push(cnt.slice(pos, i));
                pos = i;
            }

            if(i === l-1){
                arr.push(cnt.slice(pos));
            }
        }
        return arr;
    };

    var marks = {
        normal: {
            title: '',
            mark: ''
        },
        remove: {
            title: 'removed',
            mark: '-'
        },
        insert: {
            title: 'inserted',
            mark: '+'
        }
    };

    var templates = {
        table: '<table class="diff-block"><tbody>${cnt}</tbody></table>',
        line: '<tr id="line-${num}" class="line ${type}">${parts}<td>${code}</td></tr>',
        lineNumber: '<td class="line-num">${num}</td>',
        mark: '<td title="${title}" class="mark">${mark}</td>',
        code: '<span class="code ${type}">${cnt}</span>'
    };

    var getLine = function(line, i){
        return render(templates.line, {
            num: i + 1,
            type: line.type,

            parts: [
                [templates.lineNumber, {num: line.pos1}],
                [templates.lineNumber, {num: line.pos2}],
                [templates.mark, marks[line.type]]
            ].map(function(arr){
                return render(arr[0], arr[1]);
            }).join(''),

            code: line.cnt.map(function(code){
                return render(templates.code, {
                    type: code.type,
                    cnt: encodeHTML(code.cnt)
                });
            }).join('')
        });
    };

    var getTable = function(lines){
        return render(templates.table, {
            cnt: lines.map(getLine).join('')
        });
    };

    // split method ( simple / participle )
    var split = participle;

    export default class  formattedDiffBlock{
        // init(wrapper, cnt1, cnt2) {
        init(wrapper) {
            this.wrapper = wrapper;
            //this.setContent(cnt1, cnt2);
        }
        getLinesDiff() {
            var lines1 = this.cnt1.split('\n'),
                lines2 = this.cnt2.split('\n'),
                lines = [];

            var curr = {
                pos1: 0,
                pos2: 0,
                prevEnd: 0
            };

            // deal with diffs
            compare(this.cnt1, this.cnt2, '\n').diff.forEach(function(diff, i){
                var start = diff[0],
                    len = diff[1],
                    to = diff[2];

                lines1.slice(curr.prevEnd, start).forEach(function(cnt){
                    lines.push({
                        type: 'normal',
                        cnt: cnt,
                        pos1: ++curr.pos1,
                        pos2: ++curr.pos2
                    });
                });

                lines1.slice(start, start + len).forEach(function(cnt){
                    lines.push({
                        type: 'remove',
                        cnt: cnt,
                        pos1: ++curr.pos1,
                        pos2: ''
                    });
                });

                to && to.split('\n').forEach(function(cnt){
                    lines.push({
                        type: 'insert',
                        cnt: cnt,
                        pos1: '',
                        pos2: ++curr.pos2
                    });
                });

                curr.prevEnd = start + len;
            });

            // same content after the last diff
            lines1.slice(curr.prevEnd).forEach(function(cnt){
                lines.push({
                    type: 'normal',
                    cnt: cnt,
                    pos1: ++curr.pos1,
                    pos2: ++curr.pos2
                });
            });

            this.lines = lines;
        }
        getInlineDiff(){
            var lines = this.lines;

            lines.forEach(function(line, i){
                var prev = lines[i-1],
                    curr = lines[i],
                    next = lines[i+1],
                    nnext = lines[i+2];

                if(
                    (!prev || prev.type !== 'remove') &&
                    (curr.type === 'remove') &&
                    (next && next.type === 'insert') &&
                    (!nnext || nnext.type !== 'insert')
                ){
                    var prevEnd = 0,
                        origin = split(curr.cnt),
                        target = split(next.cnt),
                        originArr = [],
                        targetArr = [];

                    compare(curr.cnt, next.cnt, split).diff.forEach(function(diff, i){
                        var start = diff[0],
                            len = diff[1],
                            to = diff[2];

                        var kept = origin.slice(prevEnd, start).join('');
                        if(kept){
                            kept = {
                                type: 'normal',
                                cnt: kept
                            };
                            originArr.push(kept);
                            targetArr.push(kept);
                        }
                        
                        var removed = origin.slice(start, start + len).join('');
                        if(removed){
                            removed = {
                                type: 'remove',
                                cnt: removed
                            };
                            originArr.push(removed);
                        }

                        var inserted = to;
                        if(inserted){
                            inserted = {
                                type: 'insert',
                                cnt: inserted
                            };

                            targetArr.push(inserted);
                        }

                        prevEnd = start + len;
                    });

                    var leftKept = origin.slice(prevEnd).join('');
                    if(leftKept){
                        leftKept = {
                            type: 'normal',
                            cnt: leftKept
                        };

                        originArr.push(leftKept);
                        targetArr.push(leftKept);
                    }

                    curr.cnt = originArr;
                    next.cnt = targetArr;
                }else if(typeof line.cnt === 'string'){
                    line.cnt = [{
                        type: 'normal',
                        cnt: line.cnt
                    }];
                }
            });

            this.lines = lines;
        }
        getDiff(){
            this.getLinesDiff();
            this.getInlineDiff();
        }
        renderDiff(){
            this.wrapper.innerHTML = getTable(this.lines);
        }
        setContent(cnt1, cnt2){
            this.cnt1 = cnt1 || '';
            this.cnt2 = cnt2 || '';

            this.getDiff();
            this.renderDiff();
        }
    };
`
使用 : 
`<template>
  <div class="container">
    <div class="v-middle">
      <ul class="row v-middle-inner" id="upload">
         <h1>文件比较的地方</h1>


          <li class="list-item gateway-gap">
              <input type="file" name="file1" id="file1" />
          </li>
         <li class="list-item gateway-gap">
            
            <input type="file" name="file2" id="file2" />
         </li>
          <li class="list-item gateway-gap">
           <button class="gateway-btn-fill-info" v-on:click="diff($event)">进行比较</button>
          </li>

        <div id="diff-wrapper" class="gateway-gap"></div>



      </ul>
    </div>
  </div>
</template>




<script>

var difftool = require('universal-diff')

import formattedDiffBlock from '../utils/diffrender';
let diffviewer = new formattedDiffBlock();

  export default {
    components: {
    },
    vuex: {
      actions: {

      }
    },
    ready() {
      diffviewer.init($('#diff-wrapper'));
      // formattedDiffBlock.init($('#diff-wrapper'));

    },
    methods: {
      diff : function (event) {
        event.preventDefault();
        event.stopPropagation();

        console.log("switch 2 waf")

        var file1 = $("#upload").find('input[name="file1"]').prop('files')[0];
        var file2 = $("#upload").find('input[name="file2"]').prop('files')[0];
        console.log("filename : " + file1.name + " ;size : " + file1.size)
        console.log("filename : " + file2.name + " ;size : " + file2.size)

        // var content1 = "1";
        // var content2 = "2";
        var files = [];
        var left = 1;

        function compare(file1, file2) {
            console.log("compare here")
            // console.log("file 1 : " + file1)
            // console.log("file 2 : " + file2)
            console.log("进行比较")
            // difftool.compare(file1, file2);
            diffviewer.setContent(file1, file2);
            // formattedDiffBlock.setContent(file1, file2)
        }

        var addcontent = function(index, context){
            files[index] = context 
            if(left!=0){
                left--;
            }else{
              compare(files[0], files[1])
            }
        } 


        var reader = new FileReader();
        reader.onload = function(e) {
          addcontent(0, e.target.result)
            // content1 = e.target.result; 
            // console.log("file1 content 1 : " + content1);
        };
        reader.readAsText(file1);

        reader = new FileReader();
        reader.onload = function(e) {
          addcontent(1, e.target.result)
            // content2 = e.target.result; 
            // console.log("file1 content 2 : " + content2);
        };
        reader.readAsText(file2);

       
        
      }
    }
  }
</script>

<style lang="scss" scoped>

    .v-middle{
      text-align: center;
      margin-top:30%;
    }
    .clickable{
      text-align: center;
      cursor: pointer;
      text-decoration: none;
      width: 90px;
      height: 70px;

      padding-top: 12px;
    }
    .clickable:hover{
      text-decoration: none; 
      /*字变白,背景变绿*/
      color: #fff;
      background: #5cb85c;
      
      /*border样式*/
      border: 1px solid #5cb85c;
      -moz-border-radius: 15px;      /* Gecko browsers */
      -webkit-border-radius: 15px;   /* Webkit browsers */
      border-radius:10px;            /* W3C syntax */
      outline: 0;
    }

    .list-item{
      width:90px;
      height: 50px;
      padding-top: -50%;
      display: inline-block;
    }
    .list-item~.list-item{
      margin-left: 10%;
      margin-right: 10%;
      height: 100px;
    }

</style>`

点击比较的时候，报错 : diff.js?ce46:101 Uncaught TypeError: eq is not a function
我使用的vue.js 开发的，按理来说不应该出错才对，不是很明白。是属于 不同开发体系导致的冲突，还是说我js版本不高 ?

**Comment by xujianhai** [comment]
第二个文件片段有问题 : 
`
<script>

var difftool = require('universal-diff')
import formattedDiffBlock from '../utils/diffrender';
let diffviewer = new formattedDiffBlock();
  export default {
    components: {
    },
    ready() {
      diffviewer.init($('#diff-wrapper'));
    },
    methods: {
      diff : function (event) {
        event.preventDefault();
        event.stopPropagation();
        var file1 = $("#upload").find('input[name="file1"]').prop('files')[0];
        var file2 = $("#upload").find('input[name="file2"]').prop('files')[0];
        console.log("filename : " + file1.name + " ;size : " + file1.size)
        console.log("filename : " + file2.name + " ;size : " + file2.size)
        var files = [];
        var left = 1;
        function compare(file1, file2) {
            console.log("进行比较")
            diffviewer.setContent(file1, file2);
        }
        var addcontent = function(index, context){
            files[index] = context 
            if(left!=0){
                left--;
            }else{
              compare(files[0], files[1])
            }
        } 
        var reader = new FileReader();
        reader.onload = function(e) {
          addcontent(0, e.target.result)
        };
        reader.readAsText(file1);

        reader = new FileReader();
        reader.onload = function(e) {
          addcontent(1, e.target.result)
        };
        reader.readAsText(file2);
      }
    }
  }
</script>
`

**Comment by xujianhai** [comment]
`<script>

  var difftool = require('universal-diff')

  import formattedDiffBlock from '../utils/diffrender';
  let diffviewer = new formattedDiffBlock();

   export default {
     components: {
   
    },
    vuex: {
      actions: {

      }
    },
    ready() {
      diffviewer.init($('#diff-wrapper'));
      // formattedDiffBlock.init($('#diff-wrapper'));

    },
    methods: {
      diff : function (event) {
        event.preventDefault();
        event.stopPropagation();

        console.log("switch 2 waf")

        var file1 = $("#upload").find('input[name="file1"]').prop('files')[0];
        var file2 = $("#upload").find('input[name="file2"]').prop('files')[0];
        console.log("filename : " + file1.name + " ;size : " + file1.size)
        console.log("filename : " + file2.name + " ;size : " + file2.size)

        // var content1 = "1";
        // var content2 = "2";
        var files = [];
        var left = 1;

        function compare(file1, file2) {
            console.log("compare here")
            // console.log("file 1 : " + file1)
            // console.log("file 2 : " + file2)
            console.log("进行比较")
            // difftool.compare(file1, file2);
            diffviewer.setContent(file1, file2);
            // formattedDiffBlock.setContent(file1, file2)
        }

        var addcontent = function(index, context){
            files[index] = context 
            if(left!=0){
                left--;
            }else{
              compare(files[0], files[1])
            }
        } 


        var reader = new FileReader();
        reader.onload = function(e) {
          addcontent(0, e.target.result)
            // content1 = e.target.result; 
            // console.log("file1 content 1 : " + content1);
        };
        reader.readAsText(file1);

        reader = new FileReader();
        reader.onload = function(e) {
          addcontent(1, e.target.result)
            // content2 = e.target.result; 
            // console.log("file1 content 2 : " + content2);
        };
        reader.readAsText(file2);

       
        
      }
    }
  }
</script>`

**Comment by xujianhai** [comment]
我看了 github上面你的代码，你是做了处理
```
universal-diff/lib/core.js ： 
var defaultEqual = function(a, b){
    return a === b;
};
....
eq = eq || defaultEqual;
```
所以就更奇怪了

**Comment by nighca** [comment]
@xujianhai `eq` 是传入 `compare` 的第三个参数，这里不传就行了，会用默认的 `defaultEqual`，你这里应该是传了一个正性的值

**Comment by xujianhai** [comment]
我改了一下，是常见的 参数赋值问题，就是 参数在函数内部不可以再赋值

**Comment by nighca** [comment]
哎？什么情况下会限制参数的赋值呢

**Comment by xujianhai** [comment]
我这边使用的一个规范。。。

**Comment by xujianhai** [comment]
请问, 你可以 给一下 具体的模型吗 ？ compare 输出的很奇怪, 不是很理解

**Comment by nighca** [comment]
@xujianhai 输出是个数组，一份编辑脚本（edit script）信息，数组每一项是一次编辑的信息，具体实现：https://github.com/nighca/universal-diff/blob/master/lib/script.js#L79

形如 `[start, len, to]`，意指从位置 `start` 开始，长度为 `len` 的内容，替换为 `to` 中的内容；`to` 的值有可能是 `undefined`，即单纯删除这段内容。
